### ISSUE TITLE
WemosD1 HomeMatic mit Bmp180 Luftdruck (&Temperatur)

### ISSUE THREAD

**Issue by elbman** [jp112sdl/WemosD1_HomeMatic_Helligkeitssensor#1]
Hallo,

finde dein WemosD1 Projekt mit BH1750 Helligkeitssensor über I2C genial und habe es bereits nachgebaut. 

Perfekt wäre es, wenn es alternativ auch eine Version für den Luftdruck- und Temperatursensor BMP180 gäbe. 

Die Info über den aktuellen Luftdruck fehlt vielen in der Homematic noch bei den Wetterdaten und lässt sich ja leider nicht als einzelner Sensor von Homematic erwerben. 

Über den Arduino mit LAN Shield gibt es hier einen Vorschlag aber mit dem WemosD1 wäre es dann doch einige Nummern besser 

https://homematic-forum.de/forum/viewtopic.php?t=19900

Freue mich über deine Einschätzung

**Comment by jp112sdl** [comment]
Hallo,

die hier vorgestellten Projekte sind so wie sie sind... und sie sind OpenSource, so dass sich jeder daran bedienen und sie weiter entwickeln oder nach persönlichem Bedarf anpassen kann.

Den Luftdrucksensor anzuschließen sollte kein Problem sein. Er wird einfach parallel zum BH1750 geklemmt... Ist ja I²C Bus.

Das Problem ist nur: Wenn ich den Sensor hier mit integriere, möchte der nächste gern beim Temp-/Feuchtesensorprojekt mit drin haben, oder irgendwo anders.

**Comment by jp112sdl** [comment]
P.S.: Wenn du den BME280 nimmst, hast du gleich noch Temperatur und Luftfeuchte.

**Comment by elbman** [comment]
Danke, das verstehe ich. Werde mich bei Zeiten da mal reinarbeiten

**Comment by jp112sdl** [comment]
@elbman 
Ist nicht böse gemeint, aber man kommt sonst vom Hundertsten zum Tausendsten ;) 

Viel Erfolg!
