### ISSUE TITLE
Fehler beim flashen

### ISSUE THREAD

**Issue by lukashauck89** [jp112sdl/WemosD1_HomeMatic_Helligkeitssensor#2]
Mal ne Frage funktioniert das flashen mit dem Grafiktool unter win10 nicht? Zeigt am Ende immer "Failed To write To target flash" an. Gruß Lukas

**Comment by jp112sdl** [comment]
Das kann ich dir leider nicht beantworten, da ich kein Windows nutze.

Schau mal hier, direkt beim ESP-Hersteller, da gibts auch ein [Tool](https://www.espressif.com/en/support/download/other-tools)

**Comment by lukashauck89** [comment]
Hab es mit dem Tool getestet zeigt keinen Fehler. Komme aber nicht in den WLAN Konfig Modus. Habe nicht den Orginal wemos Baustein. Vielleicht liegt es daran. AZDelivery D1 Mini NodeMcu Lua ESP8266 ESP-12E WLAN WIFI Internet Module Entwicklungsboard für Arduino, 100% kompatibel mit WeMos D1 Mini https://www.amazon.de/dp/B01N9RXGHY/ref=cm_sw_r_cp_apa_lkQVAbM6NY749

**Comment by jp112sdl** [comment]
Taster an D7 gedrückt halten und Stromzufuhr herstellen... klappt nicht?

**Comment by lukashauck89** [comment]
Nein Led Blitz einmal wie immer dann nichts mehr.

**Comment by jp112sdl** [comment]
Dann lass dir mal mit Putty oder einem anderen Terminalprogramm die seriellen Log-Ausgaben (115200 Baud) anzeigen.

**Comment by lukashauck89** [comment]
{ll▒▒<▒l▒|
▒
d▒
#|▒▒▒▒{▒c▒
#▒▒gn▒lno▒▒▒
cp▒▒dsd;l{▒n▒c▒ncp

**Comment by lukashauck89** [comment]
das spuckt er beim reset aus

**Comment by jp112sdl** [comment]
Das ist nix... da läuft nix auf dem Wemos. 
Dann ist beim Flashen was schiefgegangen oder so. 

Da muss lesbarer Text kommen.

**Comment by lukashauck89** [comment]
Dacht ich mir.
so sieht der verlauf aus:
connecting ....
Erasing flash...

Writing at 0x00000000... (0 %)

Writing at 0x00000400... (3 %)

Writing at 0x00000800... (6 %)

Writing at 0x00000c00... (9 %)

Writing at 0x00001000... (12 %)

Writing at 0x00001400... (15 %)

Writing at 0x00001800... (18 %)

Writing at 0x00001c00... (21 %)

Writing at 0x00002000... (24 %)

Writing at 0x00002400... (27 %)

Writing at 0x00002800... (30 %)

Writing at 0x00002c00... (33 %)

Writing at 0x00003000... (36 %)

Writing at 0x00003400... (39 %)

Writing at 0x00003800... (42 %)

Writing at 0x00003c00... (45 %)

Writing at 0x00004000... (48 %)

Writing at 0x00004400... (51 %)

Writing at 0x00004800... (54 %)

Writing at 0x00004c00... (57 %)

Writing at 0x00005000... (60 %)

Writing at 0x00005400... (63 %)

Writing at 0x00005800... (66 %)

Writing at 0x00005c00... (69 %)

Writing at 0x00006000... (72 %)

Writing at 0x00006400... (75 %)

Writing at 0x00006800... (78 %)

Writing at 0x00006c00... (81 %)

Writing at 0x00007000... (84 %)

Writing at 0x00007400... (87 %)

Writing at 0x00007800... (90 %)

Writing at 0x00007c00... (93 %)

Writing at 0x00008000... (96 %)

Writing at 0x00008400... (100 %)
Failed to write to target Flash

**Comment by lukashauck89** [comment]
Die Standart Baudrate ist wohl 7400 da zeigt er auch was an.

**Comment by jp112sdl** [comment]
Hmm, da bin ich echt raus...
Noch nie gesehen sowas. 

Evtl im Flash Tool eine falsche Clock Rate eingestellt, oder der Wemos hat tatsächlich ein Problem.

**Comment by lukashauck89** [comment]
Welche Clock Rate wird benutzt? Ich werde wohl mal noch einen neuen D1 mini bestellen. Danke

**Comment by jp112sdl** [comment]
Hab mir den Kram mal in eine virtuelle Windows-Umgebung geladen.

Probier es mal mit diesen Einstellungen, damit ging es bei mir. COM1 muss natürlich noch geändert werden.
<img width="499" alt="bildschirmfoto 2018-03-31 um 10 22 08" src="https://user-images.githubusercontent.com/18190139/38161377-224265bc-34ce-11e8-87dc-4903fb09892a.png">


Putty:
<img width="558" alt="bildschirmfoto 2018-03-31 um 10 27 01" src="https://user-images.githubusercontent.com/18190139/38161382-2e184794-34ce-11e8-8a76-758cfd94c943.png">

**Comment by lukashauck89** [comment]
![unbenannt](https://user-images.githubusercontent.com/37932902/38161718-efc5bd8a-34d4-11e8-941f-886efec14439.png)

**Comment by lukashauck89** [comment]
So sieht es dann aus aber funktionieren tut es nicht. Flash ist immernoch leer

**Comment by jp112sdl** [comment]
Hast du irgendwas an D3 angeschlossen?

**Comment by lukashauck89** [comment]
Nur die Brücke auf GND zum flashen

**Comment by jp112sdl** [comment]
Aber auch wirklich nur zum Flashen?

Mit der Brücke startet der Wemos nicht... und geht immer wieder in den Flash-Modus.

Was auch deinen wirren Zeichensalat erklärt.

**Comment by lukashauck89** [comment]
ja habe sie nur zum flashen drann

**Comment by jp112sdl** [comment]
Ist auch eigentlich nur beim ESPFlasher notwendig. Mit dem Tool von Espressif brauchst du die Brücke nicht.

Hmm - also ich kann dir von hier sonst auch keine Tipps weiter geben.

**Comment by lukashauck89** [comment]
Ok ich danke dir für deine mühe ich werden mal einen neuen bestellen. Hab von einem Käufer gelesen das er es auch mal hatte das sich einer einfach nicht flashen lies.

**Comment by jp112sdl** [comment]
Ich mache kaum noch was mit den Wemos, aber ich hatte meine damals über eBay aus China bezogen, für irgendwas ~ 3 EUR pro Stück. 
Siehe zB diesen [Artikel](https://www.ebay.de/itm/ESP8266-ESP-12-NodeMcu-Lua-WeMos-D1-Mini-WiFi-Develop-Kit-Development-Board-/272271662681)

Hab hier noch so ca. 15 Stück im Einsatz und hatte noch nie Probleme beim Flashen.

Ansonsten kann ich dir empfehlen, den [HM-Sen-LI-O](https://github.com/jp112sdl/Beispiel_AskSinPP/tree/master/examples/HM-Sen-LI-O) nachzubauen.
Den kannst du dann auch direkt in Homematic anlernen.
Allgemeine Verkabelungsübersicht und benötigte Teile findest du [hier](https://github.com/jp112sdl/Beispiel_AskSinPP).
