### ISSUE TITLE
401 error if using this with curent firmware of ccu3

### ISSUE THREAD

**Issue by modwadd** [jp112sdl/WemosD1_HomeMatic_Helligkeitssensor#3]
in the http request requires to be added :
Name:Passwort@ccuip
The Name and Password requires to be a valid user on the CCU.
Would be nice if this could be configured via web config in setup mode.

**Comment by jp112sdl** [comment]
Sorry... since using AskSinPP Lib to create devices that can be used in Homematic natively I do not support the WiFi projects any longer.
https://asksinpp.de
